package handlers

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/a-h/templ"
	"github.com/go-chi/chi/v5"
	"github.com/golang-jwt/jwt/v5"

	"github.com/loxtu/loxtu-go/internal/core/audit"
	"github.com/loxtu/loxtu-go/internal/core/identity"
	"github.com/loxtu/loxtu-go/internal/shared/httputil"
	authtmpl "github.com/loxtu/loxtu-go/internal/interfaces/templates/auth"
	mw "github.com/loxtu/loxtu-go/internal/interfaces/http/middleware"
	"github.com/loxtu/loxtu-go/internal/security"
)

// PasskeyPresence reports whether the user already enrolled a passkey.
type PasskeyPresence interface {
	HasPasskey(ctx context.Context, tenantID, email string) bool
}

// AuthHandler is the HTTP surface for OTP / consent / refresh / logout.
type AuthHandler struct {
	otp      *identity.OTPService
	tokens   *identity.TokenService
	users    identity.UserStore
	audit    audit.Store
	rl       identity.RateLimiter
	passkeys PasskeyPresence // optional
	pepper   string
}

// NewAuthHandler constructs an AuthHandler with required dependencies.
func NewAuthHandler(
	otp *identity.OTPService,
	tokens *identity.TokenService,
	users identity.UserStore,
	auditStore audit.Store,
	rl identity.RateLimiter,
	passkeys PasskeyPresence,
	pepper string,
) *AuthHandler {
	return &AuthHandler{
		otp:      otp,
		tokens:   tokens,
		users:    users,
		audit:    auditStore,
		rl:       rl,
		passkeys: passkeys,
		pepper:   pepper,
	}
}

// Mount registers auth public routes.
func (h *AuthHandler) Mount(r chi.Router) {
	r.Get("/", h.LoginPage)
	r.Post("/auth/otp/send", h.SendOTP)
	r.Post("/auth/otp/verify", h.VerifyOTP)
	r.Get("/auth/consent", h.ConsentPage)
	r.Post("/auth/consent", h.ConsentAccept)
	r.Post("/auth/refresh", h.Refresh)
	r.Post("/auth/logout", h.Logout)
}

func (h *AuthHandler) LoginPage(w http.ResponseWriter, r *http.Request) {
	if httputil.WantsJSON(r) {
		httputil.WriteJSON(w, http.StatusOK, map[string]string{"type": "login", "message": "Login form endpoint"})
		return
	}
	templ.Handler(authtmpl.LoginShell()).ServeHTTP(w, r)
}

func (h *AuthHandler) SendOTP(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		httputil.WriteJSON(w, http.StatusBadRequest, map[string]string{"error": "bad request"})
		return
	}
	email := strings.TrimSpace(r.FormValue("email"))
	if email == "" || !strings.Contains(email, "@") {
		templ.Handler(authtmpl.LoginFormPartial()).ServeHTTP(w, r)
		return
	}

	if h.rl != nil {
		allowed, err := h.rl.Allow(r.Context(), identity.RateKeyOTPSend(email), identity.PolicyOTP)
		if err != nil {
			log.Printf("[auth] rate limit error: %v", err)
		}
		if !allowed {
			msg := "Too many attempts. Please wait before trying again."
			templ.Handler(authtmpl.OTPErrorPartial(email, msg)).ServeHTTP(w, r)
			return
		}
	}

	if _, err := h.otp.Send(r.Context(), email); err != nil {
		log.Printf("otp send error: %v", err)
		templ.Handler(authtmpl.LoginFormPartial()).ServeHTTP(w, r)
		return
	}

	// Resolve tenant from email domain
	tenantID := mw.GetTenantCode(r.Context())
	if tenantID == "" {
		tenantID = "public"
	}

	// Find or create user
	emailHash := security.HashEmail(email, h.pepper)
	u, err := h.users.FindByEmailHash(r.Context(), emailHash)
	userID := ""
	if err == nil && u != nil {
		userID = u.UserID
	}
	if userID == "" {
		// Create new user with UUID v7
		newUser := &identity.User{
			UserID:    "", // will be generated by repo
			EmailHash: emailHash,
			TenantID:  tenantID,
			Status:    "pending",
			IsActive:  false,
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		}
		if err := h.users.Create(r.Context(), newUser); err != nil {
			log.Printf("[auth] CRITICAL: cannot create user for %s: %v", security.MaskEmail(email), err)
			http.Error(w, "internal error", http.StatusInternalServerError)
			return
		}
		userID = newUser.UserID
	}

	// Set pre-auth cookies
	cookieVal := fmt.Sprintf(`{"email":"%s","tenant_id":"%s"}`, email, tenantID)
	http.SetCookie(w, &http.Cookie{
		Name: "pre_auth_state", Value: url.QueryEscape(cookieVal),
		Path: "/", MaxAge: 600, HttpOnly: true, Secure: true, SameSite: http.SameSiteLaxMode,
	})
	http.SetCookie(w, &http.Cookie{
		Name: "loxtu_tenant", Value: tenantID,
		Path: "/", MaxAge: 600, HttpOnly: true, Secure: true, SameSite: http.SameSiteLaxMode,
	})

	h.logSecurity(r, audit.SecurityEvent{
		UserID:      userID,
		TenantID:    tenantID,
		MaskedEmail: security.MaskEmail(email),
		Action:      "auth.otp.send",
		Status:      "success",
		ClientIP:    mw.GetClientIP(r),
		ReqID:       mw.GetRequestID(r.Context()),
	})

	templ.Handler(authtmpl.OTPFormPartial(email)).ServeHTTP(w, r)
}

func (h *AuthHandler) VerifyOTP(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad request", http.StatusBadRequest)
		return
	}
	email := r.FormValue("email")
	codes := r.Form["code"]
	code := strings.Join(codes, "")

	if h.rl != nil {
		allowed, err := h.rl.Allow(r.Context(), identity.RateKeyOTPFail(email), identity.PolicyOTP)
		if err != nil {
			log.Printf("[auth] rate limit error: %v", err)
		}
		if !allowed {
			msg := "Too many attempts. Please wait before trying again."
			templ.Handler(authtmpl.OTPErrorPartial(email, msg)).ServeHTTP(w, r)
			return
		}
	}

	if !h.otp.Verify(email, code) {
		h.logSecurity(r, audit.SecurityEvent{
			MaskedEmail: security.MaskEmail(email),
			Action:      "auth.otp.verify",
			Status:      "failure",
			ClientIP:    mw.GetClientIP(r),
			ReqID:       mw.GetRequestID(r.Context()),
		})
		templ.Handler(authtmpl.OTPErrorPartial(email, "Invalid or expired code. Try again.")).ServeHTTP(w, r)
		return
	}

	if h.rl != nil {
		_ = h.rl.Reset(r.Context(), identity.RateKeyOTPSend(email))
		_ = h.rl.Reset(r.Context(), identity.RateKeyOTPFail(email))
	}

	tenantID := mw.GetTenantCode(r.Context())
	if tenantID == "" {
		tenantID = "public"
	}

	emailHash := security.HashEmail(email, h.pepper)
	u, err := h.users.FindByEmailHash(r.Context(), emailHash)
	if err != nil || u == nil || u.UserID == "" {
		log.Printf("[auth] ERROR: user not found for %s after OTP verify", security.MaskEmail(email))
		http.Error(w, "user not found", http.StatusBadRequest)
		return
	}

	// MFA check: if tenant requires MFA and user has no passkey → require enrollment
	if h.passkeys != nil {
		// TODO: read tenant.SecurityPolicy.MFARequired from TenantStore
		// For now, check if user has passkey
		hasPasskey := h.passkeys.HasPasskey(r.Context(), tenantID, email)
		if !hasPasskey {
			// MFA not satisfied — will show passkey registration after consent
		}
		_ = hasPasskey
	}

	masked := security.MaskEmail(email)

	// Check consent
	granted := h.consentGranted(r.Context(), u.UserID, masked)
	if granted {
		if err := h.issueCookies(w, r, u.UserID, tenantID, "auth.otp.verify"); err != nil {
			log.Printf("ERROR IssueTokens: %v", err)
		} else {
			w.Header().Set("HX-Redirect", "/dashboard")
			w.WriteHeader(http.StatusOK)
		}
		return
	}

	http.SetCookie(w, &http.Cookie{
		Name: "loxtu_consent", Value: email, Path: "/",
		MaxAge: 300, HttpOnly: true, SameSite: http.SameSiteLaxMode,
	})
	h.logSecurity(r, audit.SecurityEvent{
		UserID:      u.UserID,
		TenantID:    tenantID,
		MaskedEmail: masked,
		Action:      "auth.otp.verify",
		Status:      "success",
		ClientIP:    mw.GetClientIP(r),
		ReqID:       mw.GetRequestID(r.Context()),
	})
	templ.Handler(authtmpl.ConsentPartial(email)).ServeHTTP(w, r)
}

func (h *AuthHandler) ConsentPage(w http.ResponseWriter, r *http.Request) {
	email := r.URL.Query().Get("email")
	if email == "" {
		if c, err := r.Cookie("loxtu_consent"); err == nil && c.Value != "" {
			email = c.Value
		}
	}
	if email == "" {
		http.Redirect(w, r, "/", http.StatusSeeOther)
		return
	}
	templ.Handler(authtmpl.ConsentPartial(email)).ServeHTTP(w, r)
}

func (h *AuthHandler) ConsentAccept(w http.ResponseWriter, r *http.Request) {
	email := r.FormValue("email")
	gdpr := r.FormValue("gdpr")
	nis2 := r.FormValue("nis2")
	soc2 := r.FormValue("soc2")
	if email == "" || gdpr == "" || nis2 == "" || soc2 == "" {
		templ.Handler(authtmpl.ConsentPage(email)).ServeHTTP(w, r)
		return
	}

	tenantID := mw.GetTenantCode(r.Context())
	if tenantID == "" {
		tenantID = "public"
	}

	emailHash := security.HashEmail(email, h.pepper)
	u, err := h.users.FindByEmailHash(r.Context(), emailHash)
	if err != nil || u == nil {
		log.Printf("[auth] ERROR: user not found for %s on consent accept", security.MaskEmail(email))
		http.Error(w, "user not found", http.StatusBadRequest)
		return
	}

	masked := security.MaskEmail(email)
	_ = masked // used for logging

	// Log consent event (v2)
	if h.audit != nil {
		_ = h.audit.LogSecurityEvent(r.Context(), audit.SecurityEvent{
			UserID:      u.UserID,
			TenantID:    tenantID,
			MaskedEmail: masked,
			Action:      "auth.consent.accept",
			Status:      "success",
			ClientIP:    mw.GetClientIP(r),
			ReqID:       mw.GetRequestID(r.Context()),
		})
	}

	http.SetCookie(w, &http.Cookie{Name: "loxtu_consent", Value: "", Path: "/", MaxAge: -1})
	http.SetCookie(w, &http.Cookie{Name: "loxtu_email", Value: email, Path: "/", MaxAge: 3600})
	http.SetCookie(w, &http.Cookie{
		Name: "loxtu_tenant", Value: tenantID,
		Path: "/", MaxAge: 600, HttpOnly: true, Secure: true, SameSite: http.SameSiteLaxMode,
	})

	if h.passkeys != nil && h.passkeys.HasPasskey(r.Context(), tenantID, email) {
		log.Printf("[auth] Passkey presence check result: true for %s", masked)
		_ = h.issueCookies(w, r, u.UserID, tenantID, "auth.consent.accept")
		w.Header().Set("HX-Redirect", "/dashboard")
		w.WriteHeader(http.StatusOK)
		return
	}
	log.Printf("[auth] Passkey presence check result: false for %s → showing register", masked)
	templ.Handler(authtmpl.RegisterPartial(email)).ServeHTTP(w, r)
}

func (h *AuthHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	cookie, err := r.Cookie("loxtu_refresh")
	if err != nil {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	pair, err := h.tokens.Rotate(r.Context(), cookie.Value)
	if err != nil {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	setAuthCookies(w, pair)
	w.WriteHeader(http.StatusNoContent)
}

func (h *AuthHandler) Logout(w http.ResponseWriter, r *http.Request) {
	userID := ""
	tenantID := "public"
	if c, err := r.Cookie("loxtu_access"); err == nil {
		token, _, _ := jwt.NewParser(jwt.WithoutClaimsValidation()).ParseUnverified(c.Value, &identity.AccessClaims{})
		if token != nil {
			if claims, ok := token.Claims.(*identity.AccessClaims); ok {
				userID = claims.UserID
				if claims.TenantID != "" {
					tenantID = claims.TenantID
				}
			}
		}
	}
	log.Printf("[auth] Logout for user=%s (reqid=%s)", userID, mw.GetRequestID(r.Context()))
	if userID != "" {
		if err := h.tokens.RevokeAllForUser(r.Context(), userID); err != nil {
			log.Printf("[auth] WARN: Session revocation skipped (non-fatal): %v", err)
		} else {
			h.logSecurity(r, audit.SecurityEvent{
				UserID:   userID,
				TenantID: tenantID,
				Action:   "auth.logout", Status: "success",
				ClientIP: mw.GetClientIP(r), ReqID: mw.GetRequestID(r.Context()),
			})
		}
	}
	clearAuthCookies(w)
	if r.Header.Get("HX-Request") == "true" {
		w.Header().Set("HX-Redirect", "/")
	} else {
		http.Redirect(w, r, "/", http.StatusSeeOther)
	}
}

func (h *AuthHandler) issueCookies(w http.ResponseWriter, r *http.Request, userID, tenantID, action string) error {
	pair, err := h.tokens.IssueSession(r.Context(), userID, tenantID, "worker", nil)
	if err != nil {
		return err
	}
	h.logSecurity(r, audit.SecurityEvent{
		UserID:   userID,
		TenantID: tenantID,
		Action:   action, Status: "success",
		ClientIP: mw.GetClientIP(r), ReqID: mw.GetRequestID(r.Context()),
	})
	setAuthCookies(w, pair)
	http.SetCookie(w, &http.Cookie{Name: "pre_auth_state", Value: "", Path: "/", MaxAge: -1, HttpOnly: true, Secure: true, SameSite: http.SameSiteLaxMode})
	http.SetCookie(w, &http.Cookie{
		Name: "loxtu_tenant", Value: tenantID,
		Path: "/", MaxAge: 3600, HttpOnly: true, Secure: true, SameSite: http.SameSiteLaxMode,
	})
	return nil
}

func (h *AuthHandler) consentGranted(_ context.Context, _, _ string) bool {
	// TODO: implement consent check against user_consents table
	return false
}

func (h *AuthHandler) logSecurity(r *http.Request, ev audit.SecurityEvent) {
	if h.audit == nil {
		return
	}
	_ = h.audit.LogSecurityEvent(r.Context(), ev)
}

func setAuthCookies(w http.ResponseWriter, pair identity.TokenPair) {
	http.SetCookie(w, &http.Cookie{Name: "loxtu_access", Value: pair.AccessToken, Path: "/", MaxAge: 900, HttpOnly: true, SameSite: http.SameSiteLaxMode})
	http.SetCookie(w, &http.Cookie{Name: "loxtu_refresh", Value: pair.RefreshPlain, Path: "/", MaxAge: 86400 * 30, HttpOnly: true, SameSite: http.SameSiteLaxMode})
}

func clearAuthCookies(w http.ResponseWriter) {
	http.SetCookie(w, &http.Cookie{Name: "loxtu_access", Value: "", Path: "/", MaxAge: -1})
	http.SetCookie(w, &http.Cookie{Name: "loxtu_refresh", Value: "", Path: "/", MaxAge: -1})
	clearTempAuthCookies(w)
	http.SetCookie(w, &http.Cookie{Name: "loxtu_tenant", Value: "", Path: "/", MaxAge: -1})
}

func clearTempAuthCookies(w http.ResponseWriter) {
	http.SetCookie(w, &http.Cookie{Name: "pre_auth_state", Value: "", Path: "/", MaxAge: -1, HttpOnly: true, Secure: true, SameSite: http.SameSiteLaxMode})
	http.SetCookie(w, &http.Cookie{Name: "loxtu_consent", Value: "", Path: "/", MaxAge: -1})
	http.SetCookie(w, &http.Cookie{Name: "loxtu_email", Value: "", Path: "/", MaxAge: -1})
}
